from machine_learning.machine_learning import MachineLearning
from meta_learning.meta_learning import MetaLearning
from meta_learning.tests_generator import TestsGenerator
from triangulation.triangulation import Triangulation
from training.training import Training
from data_processing.data_processing import DataProcessing