[project]
name = "climseries"
version = "0.1.0"
description = "A library for triangulation, machine learning, meta learning and trends of climatic series"
authors = [
    { name="Nathan M. Lima", email="nathan116lima@gmail.com" },
    { name="Pablo de 0. Passarini", email="pablo4passarini@gmail.com"},
    { name="Filipe J. S. Coelho", email="filipesantos.lf@gmail.com"},
    { name="Marconi A. Pereira", email="marconi@ufsj.edu.br"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "matplotlib",
    "scipy",
    "folium",
    "haversine",
    "scikit-learn",
    "numpy",
    "tksheet",
    "pyscreenshot"
]

[project.urls]
"Homepage" = "https://github.com/NathanLima1/Series"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
